- name: configuring the backend server
  hosts: localhost
  become: yes
  tasks:
  - name: Disabling Node Js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable Node Js
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: download nodeJs
    ansible.builtin.dnf:
      name: nodejs
      state: installed

  - name: Adding user
    ansible.builtin.user:
      name: expense
  
  - name: Creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download Backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip 

  - name: Unzip the code 
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app

  - name: install npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app