- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}" 
      state: "{{ item.state }}"
    loop:
    - {name: 'mysql', state: 'absent'}
    - {name: 'nginx', state: 'latest'}
    - {name: 'postfix', state: 'absent'}
  - name: start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
