- name: install and start nginx
  hosts: web
  become: yes #root
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: start nginx
      status: started
      enabled: yes